# Basic pdr.DataReader() example or explantaion

In [5]:
import pandas as pd
import pandas_datareader.data as pdr

In [9]:
dataframe_1 = pdr.DataReader('005930','naver','2022-01-01','2022-03-31')
dataframe_1

             Open   High    Low  Close    Volume
Date
2022-01-03  79400  79800  78200  78600  13502112
2022-01-04  78800  79200  78300  78700  12427416
2022-01-05  78800  79000  76400  77400  25470640
2022-01-06  76700  77600  76600  76900  12931954
2022-01-07  78100  78400  77400  78300  15163757
2022-01-10  78100  78100  77100  78000   9947422
2022-01-11  78400  79000  78000  78900  13221123
2022-01-12  79500  79600  78600  78900  11000502
2022-01-13  79300  79300  77900  77900  13889401
2022-01-14  77700  78100  77100  77300  10096725
2022-01-17  77600  77800  76900  77500   8785122
2022-01-18  77600  77800  76600  77000   9592788
2022-01-19  76500  76900  76100  76300  10598290
2022-01-20  76200  76700  75900  76500   9708168
2022-01-21  75800  75800  74700  75600  15774888
2022-01-24  75400  75800  74700  75100  13691134
2022-01-25  74800  75000  73200  74000  17766704
2022-01-26  73900  74400  73100  73300  12976730
2022-01-27  73800  74000  71300  71300  22274777
2022-01-28  71300  73700  71200  73300  21367447
2022-02-03  74900  74900  73300  73300  17744721
2022-02-04  74300  74600  73400  74000  12730034
2022-02-07  73500  73600  72400  73000  14240838
2022-02-08  73800  74200  73000  73500  11736666
2022-02-09  74300  74700  74000  74700   9699122
2022-02-10  75600  75800  74700  75400  17746033
2022-02-11  75000  75500  74600  74900  12205407
2022-02-14  74400  74500  73100  73700  13993255
2022-02-15  74100  74200  73100  73700   9320365
2022-02-16  74600  74900  74200  74800  10767386
2022-02-17  75000  75600  74500  75000  13605382
2022-02-18  74600  74800  73700  74300  10122226
2022-02-21  73200  74300  72600  74200  10489717
2022-02-22  73000  73400  72800  73400  11692469
2022-02-23  73800  73800  72800  73000  10397964
2022-02-24  72300  72300  71300  71500  15759283
2022-02-25  72100  72600  71900  71900  13168484
2022-02-28  71100  72100  71000  72100  17781783
2022-03-02  72300  72400  71500  71700  12481430
2022-03-03  72300  73100  72200  72900  13232638
2022-03-04  72700  72700  71200  71500  13409634
2022-03-07  70000  70600  69900  70100  18617138
2022-03-08  68800  70000  68700  69500  15828269
2022-03-10  70800  71200  70500  71200  21159248
2022-03-11  70500  70700  69700  70000  15787655
2022-03-14  70000  70200  69600  70200   9040993
2022-03-15  69800  70100  69500  69500  10258562
2022-03-16  70200  70500  69700  70400  10175750
2022-03-17  71200  71800  70900  71200  17646315
2022-03-18  70600  70900  70200  70700  14410038
2022-03-21  70900  71000  69900  69900  11169002
2022-03-22  69900  70500  69900  70300   9402666
2022-03-23  70600  71200  70300  70500  12398025
2022-03-24  69600  70300  69600  69800  37943357
2022-03-25  70100  70200  69600  69800  12986010
2022-03-28  69500  69900  69200  69700  12619289
2022-03-29  70000  70300  69800  70200  13686208
2022-03-30  70300  70500  69800  69900  12670187
2022-03-31  69900  70200  69600  69600  12510366

In [18]:
import pandas_datareader.data as pdr
stock = 'SPY'
source = 'yahoo'
startdate = '2022-01-01'
enddate = '2022-01-31'

stock_df =pdr.DataReader(stock, source, startdate, enddate)
print(stock_df)

TypeError: string indices must be integers